"""initial schema

Revision ID: c74653022d16
Revises: 
Create Date: 2026-08-07 19:40:47.952952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74653022d16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('ticket_key', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('epic', 'story', 'task', 'bug', 'spike', name='tickettype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('backlog', 'ready', 'in_progress', 'review', 'done', 'blocked', 'needs_human', 'agent_failed', name='ticketstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='ticketpriority', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('definition_of_done', sa.JSON(), nullable=False),
    sa.Column('relevant_files', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('estimated_complexity', sa.String(length=50), nullable=True),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sequence', name='uq_ticket_project_sequence'),
    sa.UniqueConstraint('project_id', 'ticket_key', name='uq_ticket_project_key')
    )
    op.create_index(op.f('ix_tickets_parent_id'), 'tickets', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tickets_project_id'), 'tickets', ['project_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_key'), 'tickets', ['ticket_key'], unique=False)
    op.create_table('ticket_dependencies',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'dependency_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_dependencies')
    op.drop_index(op.f('ix_tickets_ticket_key'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_project_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_parent_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('projects')
    # ### end Alembic commands ###
